name: Deploy CoinHawk Backend to cPanel

on:
  push:
    branches:
      - [main, cors-fix]

jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: 📂 Navigate to directory
        working-directory: ./
        run: echo "Switched to the directory"
      
      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ vars.FTP_PASSWORD }}
          server-dir: coinhawk-api.blockfuselabs.com/
          local-dir: './'